// Generated by CoffeeScript 1.7.1
(function() {
  var ItEbooks, http;

  http = require('http');

  ItEbooks = (function() {
    function ItEbooks() {}

    ItEbooks.baseUrl = 'http://localhost:8000/it-ebooks-api.info/v1/';

    ItEbooks.prototype._get = function(path, callback) {
      return http.get(this.baseUrl + path, function(res) {
        var body;
        body = '';
        res.on('data', function(chunk) {
          return body += chunk;
        });
        return res.on('end', function() {
          return callback(JSON.parse(body));
        });
      });
    };

    ItEbooks.prototype.search = function(query, callback) {
      return _get('/search/' + query, callback);
    };

    return ItEbooks;

  })();

  module.exports = ItEbooks;

}).call(this);
