// Generated by CoffeeScript 1.7.1
(function() {
  var ItEbooks, http;

  http = require('http');

  ItEbooks = (function() {
    function ItEbooks() {}

    ItEbooks.prototype.baseUrl = 'http://localhost:8000/it-ebooks-api.info/v1/';

    ItEbooks.prototype._get = function(path, callback) {
      var requestString;
      requestString = this.baseUrl + path;
      console.log('GET ' + requestString);
      return http.get(requestString, function(res) {
        var body;
        body = '';
        res.on('data', function(chunk) {
          return body += chunk;
        });
        return res.on('end', function() {
          return callback(JSON.parse(body));
        });
      });
    };

    ItEbooks.prototype.search = function(query, callback) {
      if (!query) {
        throw new Error('must provide a search query');
      }
      if (!callback) {
        throw new Error('must provide a callback');
      }
      return this._get('/search/' + query, callback);
    };

    return ItEbooks;

  })();

  module.exports = new ItEbooks;

}).call(this);
